"""Autopilot: daily auto-generation and scheduling of 5 posts.

Automatically determines the right strategy based on data maturity:
  - Phase 1 (bootstrap, <70 posts): Rotate all hooks evenly to gather data
  - Phase 2 (learning, 70-150 posts): Focus on top-performing hooks, still explore
  - Phase 3 (optimized, 150+ posts): Template-based + recycle, concentrate on winners

Designed to run via cron every morning, fully unattended.
"""

from __future__ import annotations

import logging
import random
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class AutopilotPlan:
    """A daily plan generated by autopilot."""

    date: str
    phase: str  # "bootstrap", "learning", "optimized"
    total_posts: int  # Total collected posts used for phase determination
    posts: list[dict] = field(default_factory=list)  # [{text, hook, source, slot}]
    skipped: list[str] = field(default_factory=list)  # Reasons for skipped posts
    scheduled: bool = False


def determine_phase(collected_count: int) -> str:
    """Determine the autopilot phase based on collected post count."""
    if collected_count < 70:
        return "bootstrap"
    elif collected_count < 150:
        return "learning"
    else:
        return "optimized"


def _get_bootstrap_hooks(
    day_index: int,
    all_hooks: list[str],
    posts_per_day: int = 5,
) -> list[str]:
    """Rotate hooks evenly across days to gather broad data.

    Each day uses a different slice of hooks so all patterns
    get tested within ~3 days.
    """
    n = len(all_hooks)
    start = (day_index * posts_per_day) % n
    selected = []
    for i in range(posts_per_day):
        selected.append(all_hooks[(start + i) % n])
    return selected


def _get_learning_hooks(
    hook_performance: dict[str, float],
    posts_per_day: int = 5,
) -> list[str]:
    """70% top performers, 30% exploration of weaker hooks."""
    sorted_hooks = sorted(hook_performance.items(), key=lambda x: x[1], reverse=True)

    n_exploit = max(1, int(posts_per_day * 0.7))  # 3-4 top hooks
    n_explore = posts_per_day - n_exploit            # 1-2 exploration

    top = [name for name, _ in sorted_hooks[:n_exploit]]
    rest = [name for name, _ in sorted_hooks[n_exploit:]]

    if rest:
        explore = random.sample(rest, min(n_explore, len(rest)))
    else:
        explore = random.sample(top, n_explore)

    return top + explore


def _get_optimized_hooks(
    hook_performance: dict[str, float],
    recyclable_count: int,
    posts_per_day: int = 5,
) -> tuple[list[str], int]:
    """Top hooks + recycle slots.

    Returns (hook_list, n_recycle) where n_recycle of the posts
    should be recycled from high-performing past posts.
    """
    sorted_hooks = sorted(hook_performance.items(), key=lambda x: x[1], reverse=True)

    # 1 recycle slot if we have recyclable posts, else all fresh
    n_recycle = min(1, recyclable_count) if recyclable_count > 0 else 0
    n_fresh = posts_per_day - n_recycle

    # Top 5 hooks, weighted by performance
    top = [name for name, _ in sorted_hooks[:n_fresh]]
    if len(top) < n_fresh:
        # Pad with random from available
        all_names = [name for name, _ in sorted_hooks]
        while len(top) < n_fresh:
            top.append(random.choice(all_names))

    return top, n_recycle


def generate_daily_plan(
    topics: list[str],
    profile: str | None = None,
    target_date: datetime | None = None,
    posts_per_day: int = 5,
) -> AutopilotPlan:
    """Generate a daily posting plan with AI content.

    Args:
        topics: List of topics/themes to generate about.
        profile: Profile name.
        target_date: Date to plan for (default: today).
        posts_per_day: Number of posts per day.

    Returns:
        AutopilotPlan with generated post texts and scheduling info.
    """
    from .config import get_settings
    from .content_generator import generate_post, generate_recycle
    from .content_guard import append_cta, check_ng
    from .content_recycler import find_recyclable_posts
    from .csv_analyzer import get_active_hooks
    from .post_history import PostHistory
    from .templates import generate_templates

    if target_date is None:
        target_date = datetime.now()

    date_str = target_date.strftime("%Y-%m-%d")
    settings = get_settings(profile=profile)
    history = PostHistory()

    # Determine phase
    collected = [r for r in history.get_all() if r.has_metrics]
    phase = determine_phase(len(collected))

    plan = AutopilotPlan(
        date=date_str,
        phase=phase,
        total_posts=len(collected),
    )

    # Get hook performance from history
    hook_performance: dict[str, float] = {}
    if collected:
        from .csv_analyzer import _detect_hooks
        for record in collected:
            hooks = _detect_hooks(record.text)
            for hook in hooks:
                if hook not in hook_performance:
                    hook_performance[hook] = 0.0
                hook_performance[hook] = max(hook_performance[hook], record.views)

    # Merge competitor research hooks (boost from trending hooks)
    try:
        from .auto_research import get_competitor_hooks
        competitor_hooks = get_competitor_hooks(profile=profile)
        for hook, avg_likes in competitor_hooks.items():
            if hook not in hook_performance:
                hook_performance[hook] = avg_likes * 10  # Scale likes to view-equivalent
            else:
                # Boost existing hooks that competitors also find effective
                hook_performance[hook] *= 1.2
    except Exception:
        pass  # Competitor data is supplementary, don't fail autopilot

    # Determine hooks for today
    all_hook_names = [name for name, _ in get_active_hooks()]
    recyclable = find_recyclable_posts(history, min_views=500)

    if phase == "bootstrap":
        day_index = (target_date - datetime(2020, 1, 1)).days
        hooks = _get_bootstrap_hooks(day_index, all_hook_names, posts_per_day)
        n_recycle = 0
    elif phase == "learning":
        if hook_performance:
            hooks = _get_learning_hooks(hook_performance, posts_per_day)
        else:
            hooks = random.sample(all_hook_names, min(posts_per_day, len(all_hook_names)))
        n_recycle = 0
    else:  # optimized
        if hook_performance:
            hooks, n_recycle = _get_optimized_hooks(
                hook_performance, len(recyclable), posts_per_day
            )
        else:
            hooks = random.sample(all_hook_names, min(posts_per_day, len(all_hook_names)))
            n_recycle = 0

    # Get templates for optimized phase
    templates = {}
    if phase == "optimized":
        for tmpl in generate_templates(history, min_views=500):
            templates[tmpl.hook_type] = tmpl

    # Generate posts
    generated_posts = []

    # Fresh posts
    n_fresh = posts_per_day - n_recycle
    # Bootstrap phase: 50% short punchy posts (1-2 lines) for virality
    n_short = n_fresh // 2 if phase == "bootstrap" else 0
    short_indices = set(random.sample(range(n_fresh), n_short)) if n_short > 0 else set()

    for i in range(n_fresh):
        hook = hooks[i] if i < len(hooks) else random.choice(all_hook_names)
        topic = topics[i % len(topics)] if topics else settings.get_research_keywords()[0] if settings.get_research_keywords() else "today's topic"
        is_short = i in short_indices

        try:
            # Use template if available in optimized phase
            if phase == "optimized" and hook in templates:
                tmpl = templates[hook]
                from .content_generator import generate_from_template
                post = generate_from_template(
                    topic=topic,
                    hook_type=hook,
                    example_posts=tmpl.example_posts,
                    best_length=tmpl.best_length_bucket,
                )
            elif is_short:
                post = generate_post(
                    topic=topic, hook_type=hook, max_length=80,
                    additional_instructions="1〜2行で端的に書いてください。短くインパクトのある投稿にしてください。余計な説明は不要です。",
                )
            else:
                post = generate_post(topic=topic, hook_type=hook)

            # NG check
            issues = check_ng(post.text)
            if issues:
                plan.skipped.append(f"NG: {hook} - {', '.join(issues)}")
                # Retry with different hook
                alt_hook = random.choice(all_hook_names)
                post = generate_post(topic=topic, hook_type=alt_hook)
                issues = check_ng(post.text)
                if issues:
                    plan.skipped.append(f"NG retry failed: {alt_hook}")
                    continue

            # Similarity check
            similar = history.check_similarity(post.text)
            if similar:
                plan.skipped.append(f"Too similar: {hook} - {post.text[:30]}...")
                post = generate_post(
                    topic=topic, hook_type=hook,
                    additional_instructions="前回と違う切り口で書いてください。"
                )

            # Add CTA
            post_text = append_cta(post.text)

            generated_posts.append({
                "text": post_text,
                "hook": hook,
                "source": post.source,
                "topic": topic,
            })

        except Exception as e:
            plan.skipped.append(f"Generation error: {hook} - {e}")
            logger.warning("Failed to generate post with hook %s: %s", hook, e)

    # Recycle posts
    for i in range(n_recycle):
        if i >= len(recyclable):
            break
        original = recyclable[i]
        unused_hooks = [h for h in all_hook_names if h not in [p.get("hook") for p in generated_posts]]
        new_hook = unused_hooks[0] if unused_hooks else random.choice(all_hook_names)

        try:
            recycled = generate_recycle(
                original_text=original.text,
                new_hook_type=new_hook,
                original_views=original.views,
            )
            post_text = append_cta(recycled.text)

            generated_posts.append({
                "text": post_text,
                "hook": new_hook,
                "source": "recycle",
                "topic": f"recycle:{original.text[:30]}",
            })
        except Exception as e:
            plan.skipped.append(f"Recycle error: {e}")

    plan.posts = generated_posts[:posts_per_day]
    return plan


def execute_plan(
    plan: AutopilotPlan,
    publish_method: str = "threads",
    profile: str | None = None,
) -> list[str]:
    """Execute a daily plan by scheduling or publishing posts.

    Args:
        plan: The autopilot plan to execute.
        publish_method: "threads" (direct) or "metricool" (scheduled).
        profile: Profile name.

    Returns:
        List of result messages.
    """
    from .config import get_settings
    from .post_history import PostHistory
    from .scheduler import get_optimal_schedule

    settings = get_settings(profile=profile)
    history = PostHistory()
    target_date = datetime.strptime(plan.date, "%Y-%m-%d")

    schedule = get_optimal_schedule(day_of_week=target_date.weekday())
    slots = schedule.slots

    results = []

    import time as _time

    MIN_INTERVAL_SEC = 30 * 60  # 30 minutes between posts

    for i, post_data in enumerate(plan.posts):
        if i >= len(slots):
            results.append(f"Skipped (no slot): {post_data['hook']}")
            continue

        # Wait 30 minutes between posts (skip wait for first post)
        if i > 0:
            logger.info("Waiting %d minutes before next post...", MIN_INTERVAL_SEC // 60)
            _time.sleep(MIN_INTERVAL_SEC)

        slot = slots[i]
        # Add random jitter (±15min) to avoid posting at exactly the same time daily
        jitter_minutes = random.randint(-15, 15)
        base_minute = slot.minute + jitter_minutes
        hour_adj = slot.hour
        if base_minute < 0:
            base_minute += 60
            hour_adj -= 1
        elif base_minute >= 60:
            base_minute -= 60
            hour_adj += 1
        hour_adj = max(0, min(23, hour_adj))

        publish_at = target_date.replace(
            hour=hour_adj, minute=base_minute, second=0, microsecond=0
        )

        text = post_data["text"]

        if publish_method == "threads":
            try:
                from .threads_api import ThreadsGraphClient
                with ThreadsGraphClient() as client:
                    post_id = client.create_text_post(text)
                    history.record_scheduled(text=text, publish_at=publish_at)
                    results.append(f"Published: {post_data['hook']} at {slot.hour}:{slot.minute:02d} (ID: {post_id})")
            except Exception as e:
                results.append(f"Failed (threads): {post_data['hook']} - {e}")
        else:  # metricool
            try:
                from .api import MetricoolClient
                from .models import PostDraft
                with MetricoolClient(profile=profile) as client:
                    client.schedule_post(PostDraft(text=text), publish_at)
                    history.record_scheduled(text=text, publish_at=publish_at)
                    results.append(f"Scheduled: {post_data['hook']} at {slot.hour}:{slot.minute:02d}")
            except Exception as e:
                results.append(f"Failed (metricool): {post_data['hook']} - {e}")

    plan.scheduled = True
    return results
