"""AI-powered content generation using Claude API."""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)

# Model used for content generation — change here to update everywhere
_MODEL = "claude-sonnet-4-20250514"


@dataclass
class GeneratedPost:
    """A post generated by AI."""

    text: str
    hook_type: str = ""
    topic: str = ""
    source: str = "ai"


def _call_with_retry(client, system_prompt: str, user_content: str, max_retries: int = 3):
    """Call Anthropic API with exponential backoff retry."""
    import time

    for attempt in range(max_retries):
        try:
            return client.messages.create(
                model=_MODEL,
                max_tokens=1024,
                system=system_prompt,
                messages=[{"role": "user", "content": user_content}],
            )
        except Exception as e:
            err_str = str(e).lower()
            is_retryable = any(k in err_str for k in ["rate", "overloaded", "timeout", "500", "502", "503", "529"])
            if not is_retryable or attempt == max_retries - 1:
                raise
            wait = 2 ** attempt
            logger.warning("Anthropic API error (attempt %d/%d), retrying in %ds: %s", attempt + 1, max_retries, wait, e)
            time.sleep(wait)


def _get_anthropic_client():
    """Get an Anthropic client, raising a helpful error if not installed."""
    try:
        import anthropic
    except ImportError:
        raise ImportError(
            "anthropic package required. Install: pip install 'snshack-threads[ai]'"
        )

    from .config import get_settings

    settings = get_settings()
    if not settings.anthropic_api_key:
        raise ValueError(
            "ANTHROPIC_API_KEY not set. Configure via profile config or environment variable."
        )
    return anthropic.Anthropic(api_key=settings.anthropic_api_key)


def _build_system_prompt(settings=None, profile: str | None = None) -> str:
    """Build the system prompt with style guide, learning data, and reference examples.

    Uses 3-tier data resolution for reference examples:
    account → genre → universal.
    Integrates content_analyzer, element_analyzer, hook_theme_matrix insights.
    """
    if settings is None:
        from .config import get_settings
        settings = get_settings(profile=profile)

    parts = [
        "あなたはThreads (Meta) でバズを狙うプロのSNSライターです。",
        "",
        "# Threadsアルゴリズムの特性",
        "- 投稿後1〜3時間の初速（リプライ・いいね率）でリーチが決まる",
        "- リプライが最重要シグナル。リプライが付く投稿は10倍以上リーチする",
        "- 保存・リポストも評価されるが、リプライ > いいね > 保存 の優先度",
        "- テキスト重視プラットフォーム。画像なしでもバズる",
        "",
        "# 絶対ルール",
        "- 500文字以内",
        "- URL・外部リンク禁止（リーチが激減する）",
        "- LINE誘導・プロフィール誘導禁止",
        "- ハッシュタグ禁止（Threadsでは逆効果）",
        "",
        "# 投稿構造のルール（これが最重要）",
        "",
        "## 1行目（フック）= 命",
        "- スクロールを止める一文。ここで9割決まる",
        "- パターン: 数字で驚かせる / 常識を否定する / 強い疑問を投げる / 危機感を煽る",
        "- 悪い例: 「補助金について解説します」→ スルーされる",
        "- 良い例: 「補助金で300万円もらった会社が、翌年に返金命令を食らった話」",
        "",
        "## 2〜3行目（引き込み）",
        "- 1行目の「なぜ？」「どういうこと？」に答える導入",
        "- 自分の実体験・実績を入れて信頼性を担保する",
        "- 「私が〇〇した結果」「〇年間〇〇してきた中で」",
        "",
        "## 本文（価値提供）",
        "- 読者が「保存したい」と思う具体的な情報を入れる",
        "- 箇条書き（✓や・）で読みやすく構造化する",
        "- 1段落3行以内。長い段落は離脱される",
        "- 空行で間を作る（詰め込みすぎない）",
        "",
        "## 最終行（CTA）= リプライを生む仕掛け",
        "- 「答えやすい具体的な質問」を置く",
        "- 悪い例: 「どう思いますか？」→ 答えにくい",
        "- 良い例: 「あなたの業界で一番使える補助金はどれ？」→ 具体的に答えられる",
        "- 二択・経験談を求める質問が効果的",
        "",
        "# 文体ルール",
        "- 「です・ます」より「だ・である」混じりの方がバズりやすい",
        "- 断言する。「かもしれません」「可能性があります」は弱い",
        "- 一次情報（自分の体験・実績ベース）で語る。評論家口調は避ける",
        "- 改行を効果的に使う。1行ずつ区切って読みやすくする",
    ]

    # Style guide
    style = settings.load_style_guide()
    if style:
        parts.append(f"\n# スタイルガイド（このアカウント固有）\n{style}")

    # Resolve reference examples with 3-tier fallback
    from .data_resolver import resolve_examples
    resolved = resolve_examples(profile=profile, n=5)
    if resolved.examples:
        tier_label = {
            "account": "このアカウントの高パフォーマンス投稿",
            "genre": "同業種の高パフォーマンス投稿",
            "universal": "全ジャンルの高パフォーマンス投稿",
        }
        label = tier_label.get(resolved.tier.value, "参考投稿")
        parts.append(f"\n# 参考投稿（{label}）")
        parts.append("以下の投稿の「1行目の構造」「改行のリズム」「CTAの具体性」を分析し、同じレベルの品質を目指してください：")
        for i, ex in enumerate(resolved.examples, 1):
            parts.append(f"\n【例{i}】\n{ex[:300]}")

    # Content factor analysis (from content_analyzer)
    try:
        from .content_analyzer import analyze_content_factors, summarize_top_factors
        from .post_history import PostHistory
        from .config import get_settings as _gs0
        _s0 = _gs0(profile=profile)
        _h0 = PostHistory(history_path=_s0.profile_dir / "post_history.json")
        collected = [r for r in _h0.get_all() if r.has_metrics]
        content_insights = analyze_content_factors(collected)
        if content_insights:
            parts.append("\n# データ分析: 何がviewsに効くか")
            parts.append("このアカウントの実績データから判明した事実。これに従って投稿を作成せよ：")
            for ci in content_insights[:8]:
                direction = "↑効果あり" if ci.lift_vs_average >= 1.0 else "↓効果なし"
                pct = (ci.lift_vs_average - 1.0) * 100
                parts.append(
                    f"  - {ci.factor}={ci.value_range}: "
                    f"平均{ci.avg_views:.0f}views ({direction}, 全体比{pct:+.0f}%, {ci.sample_count}件)"
                )
    except Exception:
        pass

    # Element analysis insights
    try:
        from .element_analyzer import analyze_elements_batch
        from .post_history import PostHistory
        from .config import get_settings as _gs
        _settings = _gs(profile=profile)
        _history = PostHistory(history_path=_settings.profile_dir / "post_history.json")
        element_stats = analyze_elements_batch(_history)
        if element_stats:
            parts.append("\n# データ分析: 構造要素の効果")
            for stat in element_stats[:6]:
                category, value = stat.pattern.split(":", 1)
                label_map = {
                    "length": "文字数", "cta": "CTA種別", "emoji": "絵文字",
                    "question": "質問形", "numbers": "数字使用",
                }
                cat_label = label_map.get(category, category)
                parts.append(f"  - {cat_label}={value}: 平均{stat.avg_views:.0f}views ({stat.post_count}件)")
    except Exception:
        pass

    # Hook × theme matrix insights
    try:
        from .hook_theme_matrix import load_matrix, get_top_combinations
        from .config import get_settings as _gs2
        _settings2 = _gs2(profile=profile)
        matrix = load_matrix(_settings2.profile_dir)
        top_combos = get_top_combinations(matrix, n=5)
        if top_combos:
            parts.append("\n# データ分析: フック×テーマの勝ちパターン")
            parts.append("以下の組み合わせが実績で証明済み。積極的に使え：")
            for combo in top_combos:
                parts.append(
                    f"  - 【{combo['hook_type']}】×【{combo['theme']}】: "
                    f"平均{combo['avg_views']:.0f}views ({combo['count']}件)"
                )
    except Exception:
        pass

    return "\n".join(parts)


def generate_post(
    topic: str,
    hook_type: str = "",
    tone: str = "",
    profile: str | None = None,
    max_retries: int = 2,
    length: str = "medium",
) -> GeneratedPost:
    """Generate a single post draft using AI.

    Args:
        topic: Topic/theme for the post.
        hook_type: Hook pattern to use (e.g. 数字訴求, 疑問形).
        tone: Tone of voice override.
        length: "short" (1-2行), "medium" (100-300字), or "long" (300-500字).
    """
    client = _get_anthropic_client()

    prompt_parts = [f"以下のトピックでThreads投稿を1つ作成してください。\n\nトピック: {topic}"]
    if hook_type:
        prompt_parts.append(f"\nフックパターン: {hook_type}")
        prompt_parts.append(f"→ 1行目で必ず「{hook_type}」のテクニックを使うこと。")
    if tone:
        prompt_parts.append(f"\nトーン指示: {tone}")

    if length == "short":
        prompt_parts.append("\n【短文投稿】1〜2行（50文字以内）。キレのある一言で刺さる内容。余計な説明は一切不要。")
    elif length == "long":
        prompt_parts.append("\n【長文投稿】300〜500文字。段落分け・箇条書きで読みやすく構造化すること。")
    else:
        prompt_parts.append("\n【中文投稿】100〜300文字。読み応えがありつつスクロールで読み切れる長さ。")

    prompt_parts.append("\n重要:")
    prompt_parts.append("- 1行目は「スクロールを止めるフック」。ここに全力を注げ")
    prompt_parts.append("- 最終行は「リプライしたくなる具体的な質問」")
    prompt_parts.append("- 投稿テキストのみを出力。説明・前置き・「」の囲みは不要")

    message = _call_with_retry(
        client, _build_system_prompt(profile=profile),
        "\n".join(prompt_parts),
    )

    text = message.content[0].text.strip()

    # Check similarity with recent posts and retry if too similar
    try:
        from .config import get_settings as _gs
        from .post_history import PostHistory
        _settings = _gs(profile=profile)
        _history = PostHistory(history_path=_settings.profile_dir / "post_history.json")
        similar = _history.check_similarity(text)
        retry_count = 0
        while similar and retry_count < max_retries:
            logger.info("Generated post too similar to existing, retrying (%d/%d)", retry_count + 1, max_retries)
            prompt_parts_retry = list(prompt_parts)
            prompt_parts_retry.append(f"\n注意: 以下の既存投稿と異なる内容にしてください:\n「{similar[0].text[:100]}」")
            message = _call_with_retry(
                client, _build_system_prompt(profile=profile),
                "\n".join(prompt_parts_retry),
            )
            text = message.content[0].text.strip()
            similar = _history.check_similarity(text)
            retry_count += 1
    except Exception as e:
        logger.debug("Similarity check skipped: %s", e)

    return GeneratedPost(text=text, hook_type=hook_type, topic=topic)


def generate_from_template(
    topic: str,
    hook_type: str,
    example_posts: list[str],
    best_length: str = "medium",
) -> GeneratedPost:
    """Generate a post based on winning templates.

    Args:
        topic: Topic for the new post.
        hook_type: Hook pattern from the template.
        example_posts: Example texts from high-performing posts.
        best_length: Target length bucket (short/medium/long).
    """
    client = _get_anthropic_client()

    length_guide = {
        "short": "100文字以内の短い投稿",
        "medium": "100〜300文字の中程度の投稿",
        "long": "300〜500文字の長めの投稿",
    }

    examples_text = "\n".join(f"  - {ex[:200]}" for ex in example_posts)

    prompt = (
        f"以下のトピックで、成功パターンに基づいたThreads投稿を作成してください。\n\n"
        f"トピック: {topic}\n"
        f"フックパターン: {hook_type}\n"
        f"文字数目安: {length_guide.get(best_length, '100〜300文字')}\n\n"
        f"参考となる高パフォーマンス投稿:\n{examples_text}\n\n"
        f"これらの構造とトーンを参考に、新しい投稿を1つ作成してください。\n"
        f"投稿テキストのみを出力してください。"
    )

    message = _call_with_retry(client, _build_system_prompt(), prompt)

    text = message.content[0].text.strip()
    return GeneratedPost(text=text, hook_type=hook_type, topic=topic, source="template")


def generate_recycle(
    original_text: str,
    new_hook_type: str = "",
    original_views: int = 0,
) -> GeneratedPost:
    """Rewrite a high-performing post with a different hook.

    Args:
        original_text: Original post text to recycle.
        new_hook_type: New hook pattern to apply.
        original_views: Original views count for context.
    """
    client = _get_anthropic_client()

    prompt = (
        f"以下の投稿は{original_views:,}回閲覧された高パフォーマンス投稿です。\n"
        f"このコンテンツの核となるメッセージを活かしつつ、全く新しい投稿として書き直してください。\n\n"
        f"元の投稿:\n{original_text}\n\n"
    )
    if new_hook_type:
        prompt += f"新しいフックパターン: {new_hook_type}\n\n"
    prompt += "投稿テキストのみを出力してください。元の投稿のコピペは避けてください。"

    message = _call_with_retry(client, _build_system_prompt(), prompt)

    text = message.content[0].text.strip()
    return GeneratedPost(text=text, hook_type=new_hook_type, source="recycle")


def generate_ab_variants(
    topic: str,
    hook_a: str,
    hook_b: str,
) -> tuple[GeneratedPost, GeneratedPost]:
    """Generate two A/B test variants with different hooks.

    Args:
        topic: Shared topic for both variants.
        hook_a: Hook pattern for variant A.
        hook_b: Hook pattern for variant B.

    Returns:
        Tuple of (variant_a, variant_b).
    """
    client = _get_anthropic_client()

    prompt = (
        f"以下のトピックで、2つの異なるフックパターンの投稿を作成してください。\n\n"
        f"トピック: {topic}\n\n"
        f"バリアントA（{hook_a}）:\n"
        f"バリアントB（{hook_b}）:\n\n"
        f"それぞれの投稿を以下の形式で出力してください：\n"
        f"---A---\n[バリアントAの投稿テキスト]\n---B---\n[バリアントBの投稿テキスト]"
    )

    message = _call_with_retry(client, _build_system_prompt(), prompt)

    response = message.content[0].text.strip()

    # Parse A/B variants
    text_a = ""
    text_b = ""
    if "---B---" in response:
        parts = response.split("---B---")
        text_a = parts[0].replace("---A---", "").strip()
        text_b = parts[1].strip()
    elif "---A---" in response:
        text_a = response.replace("---A---", "").strip()
    else:
        text_a = response
        text_b = response

    return (
        GeneratedPost(text=text_a, hook_type=hook_a, topic=topic, source="ab_test"),
        GeneratedPost(text=text_b, hook_type=hook_b, topic=topic, source="ab_test"),
    )


def generate_batch(
    topics: list[str],
    hook_types: list[str] | None = None,
    tone: str = "",
) -> list[GeneratedPost]:
    """Generate multiple posts at once.

    Args:
        topics: List of topics (one per post).
        hook_types: Optional hook patterns to cycle through.
        tone: Tone of voice.

    Returns:
        List of GeneratedPost.
    """
    results = []
    for i, topic in enumerate(topics):
        hook = ""
        if hook_types:
            hook = hook_types[i % len(hook_types)]
        post = generate_post(topic=topic, hook_type=hook, tone=tone)
        results.append(post)
    return results
